travis:
  secure:
    BINSTAR_TOKEN: LhEFB7bPt2StrcBol8VYLSgml0H+2F/bd8M65pA97VuHXZFoXvebzOPKaaij5zdPrndetFPBbmKgJlyHU1Po29mSje4d1irP/w2FyyjJUGHXZU+GNPgoFBykuREibm3WHOx2Cfan0U2H3cK7Ofct3Hn4amKlreGuEQDqYLZdfbtemvMuewA/jLk4DUEwg2pyfSPtZlCcCTFXUKVpqYQO488nXKAThrtAngEK751AobNlsCAmhtBA3f8rLn8UPDcY2MNF+mE0y5C6emtnyeC6VNl10PGcXkcVQnu7dq+LUfYmjM+ZKUElscIFjPPVV+9cDlbPQVMpMxAsYFre7QwcM01YVzblucyVzj2TTz0TBXidjP89ig+oCGwMwS2QF3r5A3wGdLW49rI4dB7wpynYQwD2lHFY6JImfAqUPh+VCo7nZBTl4NhBi0pSjmfsh0NfCBPX59L1YKz49BbdVNMPRTrRcN2VzbssZT43uaxpO9rMM/bt6xbdYtoXHmCi209NLQiy/KWSmsBdYckai+V04K/YaXXys1wvyHxJY8tCIKmwd5vPbGTw0ZRRBGVo4zWsj5YRW72gdVm1uNLvA88OAPM5HffeUgm8ZJSjauSsA1F5bXjVzVSU18DakljGq2qFINBEUzTR/ZVZy0o1oYYIcVcVxK+IYxSN280TlnYDjU0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
